# Generated by Django 5.0 on 2024-02-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="option4",
            field=models.CharField(default="-", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_option",
            field=models.CharField(max_length=2),
        ),
    ]
