# Generated by Django 5.0 on 2024-02-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_app", "0002_question_option4_alter_question_correct_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_option",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="chosen_option",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
