# Generated by Django 5.0 on 2024-02-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_app", "0003_alter_question_correct_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_option",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="chosen_option",
            field=models.CharField(max_length=1),
        ),
    ]
